version: '3.6'

services:
  webapplication3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44322
      - DEFAULT_CONNECTION_STRING=Server=sql.data;Database=identityTest;User Id=sa;Password=Str0ngPa55word!
    ports:
      - "57329:80"
      - "44322:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  sql.data:
    environment:
      - SA_PASSWORD=Str0ngPa55word!
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"